# -*- coding: utf-8 -*-
u"""Qt compatibility shim -- PySide2 hard-pin for Maya 2022.

M_P0_MAYA_2022_FROM_SCRATCH Phase 11 R5: this file replaces the
scripts/RBFtools/ui/compat.py try-PySide6 / fall-back-PySide2
dispatch with a direct PySide2 import. Maya 2022 has no PySide6 /
shiboken6, so the original try block always raised ImportError;
removing it eliminates a spurious exception at every module load
and makes the import path easy to audit.

The forward-compat patches (QAction, QShortcut, QActionGroup) are
kept as no-ops in Qt5: the if-not-hasattr guards never fire because
PySide2 already exposes those classes on QtWidgets. The block is
retained for code symmetry with scripts/ so call sites can use
QtWidgets.QAction unconditionally regardless of which scripts tree
is on sys.path.

Auto-generated by tools/sync_2022_from_2025.py -- do not hand-edit.
"""
from __future__ import absolute_import

# ------------------------------------------------------------------
# PySide2 hard-pin (Maya 2022)
# ------------------------------------------------------------------

from PySide2 import QtWidgets, QtCore, QtGui   # noqa: F401
from shiboken2 import wrapInstance              # noqa: F401
BINDING = "PySide2"

# ------------------------------------------------------------------
# Convenience aliases
# ------------------------------------------------------------------

Signal   = QtCore.Signal
Slot     = QtCore.Slot
Property = QtCore.Property

# ------------------------------------------------------------------
# Forward-compat patches (no-ops on PySide2; kept for code symmetry
# with scripts/ so call sites can always do QtWidgets.QAction).
# ------------------------------------------------------------------

if not hasattr(QtWidgets, "QAction"):
    QtWidgets.QAction = QtGui.QAction
if not hasattr(QtWidgets, "QShortcut"):
    QtWidgets.QShortcut = QtGui.QShortcut
if not hasattr(QtWidgets, "QActionGroup"):
    QtWidgets.QActionGroup = QtGui.QActionGroup

# ------------------------------------------------------------------
# Maya main window helper
# ------------------------------------------------------------------

import maya.OpenMayaUI as omui


def maya_main_window():
    """Return the Maya main window as a QWidget.

    Returns None when called outside a GUI session (e.g. mayapy).
    """
    ptr = omui.MQtUtil.mainWindow()
    if ptr is not None:
        return wrapInstance(int(ptr), QtWidgets.QWidget)
    return None
